#!/usr/bin/env zsh
alias twitch='google-chrome-stable dashboard.twitch.tv/u/retrotechnoatl/stream-manager --profile-directory="Default" '
alias lilive='google-chrome-stable linkedin.com/video/golive/now/ --profile-directory="Default" '
alias fblive='google-chrome-stable https://www.facebook.com/live/producer/v2/ --profile-directory="Default" '
alias ytlive='google-chrome-stable studio.youtube.com/channel/UCDzFboeQNS_LP-Vy3VtbT7g/livestreaming --profile-directory="Default" '
alias tweet='google-chrome-stable twitter.com --profile-directory="Default" '
alias gcp='google-chrome-stable gcp.trau.co --profile-directory="Default" '
alias gsuite='google-chrome-stable admin.google.com --profile-directory="Default" '
alias mail='google-chrome-stable gmail.com --profile-directory="Default" '
alias cal='google-chrome-stable calendar.google.com/calendar/u/0/r --profile-directory="Default" '
alias drive='google-chrome-stable drive.google.com --profile-directory="Default" '
alias gh='google-chrome-stable github.cloudyeng.com --profile-directory="Default" '
alias slack='google-chrome-stable trauco.slack.com --profile-directory="Default" '
alias bc-support='google-chrome-stable https://botcopysupport.slack.com --profile-directory="Profile 1" '
alias bc-ent='google-chrome-stable https://botcopy.slack.com/ --profile-directory="Profile 1" '
alias bc-gmail='google-chrome-stable gmail.com --profile-directory="Profile 1" '
alias bc-cal='google-chrome-stable calendar.google.com --profile-directory="Profile 1" '
